ci: add wasm publish

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,118 +1,118 @@
 name: Build and upload assets
 on:
   release:
-    types: [ published ]
+    types: [published]
 
 jobs:
-  build:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        # Build gnu-linux on ubuntu-18.04 and musl on ubuntu latest
-        # os: [ ubuntu-18.04, ubuntu-latest, windows-latest, macos-latest ]
-        os: [ ubuntu-latest, windows-latest, macos-latest ]
-    name: Building, ${{ matrix.os }}
-    steps:
-      - name: Fix CRLF on Windows
-        if: runner.os == 'Windows'
-        run: git config --global core.autocrlf false
+  # build:
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # Build gnu-linux on ubuntu-18.04 and musl on ubuntu latest
+  #       # os: [ ubuntu-18.04, ubuntu-latest, windows-latest, macos-latest ]
+  #       os: [ ubuntu-latest, windows-latest, macos-latest ]
+  #   name: Building, ${{ matrix.os }}
+  #   steps:
+  #     - name: Fix CRLF on Windows
+  #       if: runner.os == 'Windows'
+  #       run: git config --global core.autocrlf false
 
-      - name: Checkout sources
-        uses: actions/checkout@v3
+  #     - name: Checkout sources
+  #       uses: actions/checkout@v3
 
-      - name: Install Protoc
-        uses: arduino/setup-protoc@v3
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Install Protoc
+  #       uses: arduino/setup-protoc@v3
+  #       with:
+  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Install stable toolchain
-        uses: dtolnay/rust-toolchain@stable
+  #     - name: Install stable toolchain
+  #       uses: dtolnay/rust-toolchain@stable
 
-      - name: Cache Cargo Build Outputs
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            target/
-          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+  #     - name: Cache Cargo Build Outputs
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: |
+  #           ~/.cargo/bin/
+  #           ~/.cargo/registry/index/
+  #           ~/.cargo/registry/cache/
+  #           ~/.cargo/git/db/
+  #           target/
+  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
 
-      - name: Cache Toolchain
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/x-tools
-          key: ${{ runner.os }}-musl-${{ hashFiles('**/musl-toolchain/preset.sh') }}
-          restore-keys: |
-            ${{ runner.os }}-musl-
+  #     - name: Cache Toolchain
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           ~/x-tools
+  #         key: ${{ runner.os }}-musl-${{ hashFiles('**/musl-toolchain/preset.sh') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-musl-
 
-      - name: Build on Linux
-        if: runner.os == 'Linux'
-        # We're using musl to make the binaries statically linked and portable
-        run: |
-          # Run build script for musl toolchain
-          source musl-toolchain/build.sh
-          
-          # Go back to the workspace
-          cd $GITHUB_WORKSPACE
-          
-          # Build for musl
-          cargo --verbose build --bin kaspad --bin rothschild --bin kaspa-wallet --release --target x86_64-unknown-linux-musl
-          mkdir bin || true
-          cp target/x86_64-unknown-linux-musl/release/kaspad bin/
-          cp target/x86_64-unknown-linux-musl/release/rothschild bin/
-          cp target/x86_64-unknown-linux-musl/release/kaspa-wallet bin/
-          archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-linux-amd64.zip"
-          asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-linux-amd64.zip"
-          zip -r "${archive}" ./bin/*
-          echo "archive=${archive}" >> $GITHUB_ENV
-          echo "asset_name=${asset_name}" >> $GITHUB_ENV
+  #     - name: Build on Linux
+  #       if: runner.os == 'Linux'
+  #       # We're using musl to make the binaries statically linked and portable
+  #       run: |
+  #         # Run build script for musl toolchain
+  #         source musl-toolchain/build.sh
 
-      - name: Build on Windows
-        if: runner.os == 'Windows'
-        shell: bash
-        run: |
-          cargo build --bin kaspad --release
-          cargo build --bin rothschild --release
-          cargo build --bin kaspa-wallet --release
-          mkdir bin || true
-          cp target/release/kaspad.exe bin/
-          cp target/release/rothschild.exe bin/
-          cp target/release/kaspa-wallet.exe bin/
-          archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-win64.zip"
-          asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-win64.zip"
-          powershell "Compress-Archive bin/* \"${archive}\""
-          echo "archive=${archive}" >> $GITHUB_ENV
-          echo "asset_name=${asset_name}" >> $GITHUB_ENV
+  #         # Go back to the workspace
+  #         cd $GITHUB_WORKSPACE
 
-      - name: Build on MacOS
-        if: runner.os == 'macOS'
-        run: |
-          cargo build --bin kaspad --release
-          cargo build --bin rothschild --release
-          cargo build --bin kaspa-wallet --release
-          mkdir bin || true
-          cp target/release/kaspad bin/
-          cp target/release/rothschild bin/
-          cp target/release/kaspa-wallet bin/
-          archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-osx.zip"
-          asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-osx.zip"
-          zip -r "${archive}" ./bin/*
-          echo "archive=${archive}" >> $GITHUB_ENV
-          echo "asset_name=${asset_name}" >> $GITHUB_ENV
+  #         # Build for musl
+  #         cargo --verbose build --bin kaspad --bin rothschild --bin kaspa-wallet --release --target x86_64-unknown-linux-musl
+  #         mkdir bin || true
+  #         cp target/x86_64-unknown-linux-musl/release/kaspad bin/
+  #         cp target/x86_64-unknown-linux-musl/release/rothschild bin/
+  #         cp target/x86_64-unknown-linux-musl/release/kaspa-wallet bin/
+  #         archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-linux-amd64.zip"
+  #         asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-linux-amd64.zip"
+  #         zip -r "${archive}" ./bin/*
+  #         echo "archive=${archive}" >> $GITHUB_ENV
+  #         echo "asset_name=${asset_name}" >> $GITHUB_ENV
 
-      - name: Upload release asset
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ github.event.release.upload_url }}
-          asset_path: "./${{ env.archive }}"
-          asset_name: "${{ env.asset_name }}"
-          asset_content_type: application/zip
+  #     - name: Build on Windows
+  #       if: runner.os == 'Windows'
+  #       shell: bash
+  #       run: |
+  #         cargo build --bin kaspad --release
+  #         cargo build --bin rothschild --release
+  #         cargo build --bin kaspa-wallet --release
+  #         mkdir bin || true
+  #         cp target/release/kaspad.exe bin/
+  #         cp target/release/rothschild.exe bin/
+  #         cp target/release/kaspa-wallet.exe bin/
+  #         archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-win64.zip"
+  #         asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-win64.zip"
+  #         powershell "Compress-Archive bin/* \"${archive}\""
+  #         echo "archive=${archive}" >> $GITHUB_ENV
+  #         echo "asset_name=${asset_name}" >> $GITHUB_ENV
+
+  #     - name: Build on MacOS
+  #       if: runner.os == 'macOS'
+  #       run: |
+  #         cargo build --bin kaspad --release
+  #         cargo build --bin rothschild --release
+  #         cargo build --bin kaspa-wallet --release
+  #         mkdir bin || true
+  #         cp target/release/kaspad bin/
+  #         cp target/release/rothschild bin/
+  #         cp target/release/kaspa-wallet bin/
+  #         archive="bin/rusty-kaspa-${{ github.event.release.tag_name }}-osx.zip"
+  #         asset_name="rusty-kaspa-${{ github.event.release.tag_name }}-osx.zip"
+  #         zip -r "${archive}" ./bin/*
+  #         echo "archive=${archive}" >> $GITHUB_ENV
+  #         echo "asset_name=${asset_name}" >> $GITHUB_ENV
+
+  #     - name: Upload release asset
+  #       uses: actions/upload-release-asset@v1
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       with:
+  #         upload_url: ${{ github.event.release.upload_url }}
+  #         asset_path: "./${{ env.archive }}"
+  #         asset_name: "${{ env.asset_name }}"
+  #         asset_content_type: application/zip
 
   build-wasm:
     runs-on: ubuntu-latest
@@ -149,34 +149,26 @@ jobs:
         # gcc-multilib allows clang to find gnu libraries properly
         run: sudo apt install -y gcc-multilib
 
-      - name: Install stable toolchain
-        if: steps.install_llvm.outcome == 'success' && steps.install_llvm.conclusion == 'success'
-        uses: dtolnay/rust-toolchain@stable
+      # install rust
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+        with:
+          toolchain: 1.89.0
+          target: wasm32-unknown-unknown
+          # key based on branch name
+          cache-shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+          cache-workspaces: ./cipher -> target
+          cache-workspace-crates: true
 
       - name: Install wasm-pack
         run: cargo install wasm-pack
 
-      - name: Add wasm32 target
-        run: rustup target add wasm32-unknown-unknown
-
       - name: Install NodeJS
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: "20"
 
       - name: Install NodeJS dependencies
         run: npm install --global typedoc typescript
-
-      - name: Cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            target/
-          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
 
       - name: Build WASM32 SDK
         run: |
